#:schema node_modules/wrangler/config-schema.json
name = "fullstack-template"

compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-12-30"
pages_build_output_dir = "./build/client"
